import { useEffect } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Check, ChevronRight, ShieldCheck, Zap, RefreshCw, Mail, Paperclip } from "lucide-react";
import { useTheme } from "@/hooks/use-theme";

const data:any={
 features:{eyebrow:"FEATURES",title:"A better disposable inbox",desc:"PN Temp Mail gives you a fast, focused temporary email workspace without unnecessary account creation."},
 how:{eyebrow:"HOW IT WORKS",title:"Create. Receive. Reset.",desc:"A simple flow designed for quick one-time email receiving."},
 faq:{eyebrow:"FAQ",title:"Frequently asked questions",desc:"Clear answers about PN Temp Mail, temporary inboxes and the web app."},
 privacy:{eyebrow:"PRIVACY",title:"Privacy-first by design",desc:"Use disposable mail carefully and never rely on it for sensitive or permanent communication."},
 about:{eyebrow:"ABOUT",title:"Meet PN Temp Mail",desc:"A clean, modern disposable email experience built around speed and simplicity."}
};

export default function InfoPage({type}:{type:keyof typeof data}){
 const {theme,toggleTheme}=useTheme(); const d=data[type];
 useEffect(()=>{document.title=`${d.title} | PN Temp Mail`},[d.title]);
 return <div className="min-h-screen bg-background"><header className="sticky top-0 z-50 border-b border-border/70 bg-background/80 backdrop-blur-2xl"><div className="max-w-6xl mx-auto h-16 px-4 flex justify-between items-center"><Link to="/" className="flex items-center gap-3"><span className="brand-mark"><Mail size={19}/></span><b className="font-display">PN <span className="text-gradient-primary">TEMP MAIL</span></b></Link><div className="flex gap-2"><button className="icon-btn" onClick={toggleTheme}>{theme==="dark"?"☀":"☾"}</button><Link to="/" className="primary-btn !py-2.5">Open inbox</Link></div></div></header>
 <main className="max-w-4xl mx-auto px-4 py-10 md:py-16"><Link to="/" className="back-link"><ArrowLeft size={16}/> Back to inbox</Link><p className="eyebrow mt-9">{d.eyebrow}</p><h1 className="page-title">{d.title}</h1><p className="page-desc">{d.desc}</p>
 {type==="features"&&<Feature/>}{type==="how"&&<How/>}{type==="faq"&&<Faq/>}{type==="privacy"&&<Privacy/>}{type==="about"&&<About/>}
 </main><footer className="border-t border-border py-8"><div className="max-w-4xl mx-auto px-4 flex flex-wrap justify-between gap-4 text-sm text-muted-foreground"><span>© {new Date().getFullYear()} PN Temp Mail</span><div className="flex gap-4"><Link to="/privacy">Privacy</Link><Link to="/faq">FAQ</Link><Link to="/about">About</Link></div></div></footer></div>
}
function Feature(){const items=[["⚡","Instant generation","Create a new disposable address in one tap."],["🔄","Live refresh","Inbox updates automatically while you wait."],["🛡️","No signup","Use the core temporary inbox without registration."],["📎","Attachments","Open available attachments from received messages."],["📱","Responsive","A polished experience across mobile and desktop."],["🔗","QR sharing","Turn an address into a scannable QR code."]];return <div className="feature-grid mt-9">{items.map(([i,t,p])=><div className="feature-card" key={t}><span className="feature-emoji">{i}</span><h3>{t}</h3><p>{p}</p></div>)}</div>}
function How(){return <div className="steps mt-9">{[["Generate","Pick natural, random, or custom and create an inbox."],["Receive","Keep the page open while incoming messages arrive."],["Read","Open a message to view its available content and attachments."],["Reset","Delete the active inbox and start with a new address."]].map(([t,p],i)=><div className="step" key={t}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{t}</h3><p>{p}</p></div></div>)}</div>}
function Faq(){const q=[["What is a temporary email?","A temporary email is a disposable address intended for short-lived email receiving."],["Do I need an account?","No. The core inbox experience is designed to work without registration."],["How frequently is the inbox checked?","The current frontend checks the configured backend every 10 seconds while the inbox is open."],["Can I use a custom username?","Yes, when the selected backend domain is available, you can enter a custom username."],["Should I use it for important accounts?","No. Disposable inboxes are not appropriate for passwords, recovery codes, financial records, or other important information."]];return <div className="faq-list mt-9">{q.map(([a,b])=><details key={a}><summary>{a}<ChevronRight/></summary><p>{b}</p></details>)}</div>}
function Privacy(){return <div className="prose mt-9"><div className="about-box"><ShieldCheck/><div><b>Privacy principle</b><p>Use the least information necessary and avoid sensitive data.</p></div></div><h3>Browser storage</h3><p>The frontend stores the active inbox address and mode locally so the session can be restored.</p><h3>Temporary means temporary</h3><p>Do not treat a disposable mailbox as a permanent archive. Messages may be removed by the backend according to its retention policy.</p><h3>Responsible use</h3><p>Do not use PN Temp Mail for fraud, abuse, harassment, unlawful activity, or bypassing a service's rules.</p></div>}
function About(){return <div className="prose mt-9"><p><strong>PN Temp Mail</strong> is a modern disposable email interface focused on a fast inbox, clean navigation and privacy-conscious usage.</p><div className="feature-grid"><div className="feature-card"><Zap/><h3>Fast</h3><p>Generate an address without a long setup flow.</p></div><div className="feature-card"><RefreshCw/><h3>Live</h3><p>Automatic inbox polling keeps the experience current.</p></div><div className="feature-card"><Paperclip/><h3>Useful</h3><p>Message details and supported attachments stay in one place.</p></div></div></div>}
