name = "ahcm-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ahcm-db"
database_id = "6eae38d5-4526-4d7a-a8f0-94197c806d9b"

[triggers]
crons = ["0 * * * *"]

[email]


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
